### ISSUE TITLE
Add code

### ISSUE THREAD

**Issue by impredicative** [HKUST-KnowComp/ASER#1]
https://arxiv.org/pdf/1905.00270v1.pdf says:

> The proposed ASER and supporting packages are available at: https://github.com/HKUST-KnowComp/ASER.

Are they?

**Comment by panda0881** [comment]
We are working on it and the data will soon be released via our homepage: https://hkust-knowcomp.github.io/ASER/.

Other supporting packages will be released in this repo.

Best Regards,
Hongming
