### ISSUE TITLE
ModuleNotFoundError while using client/server mode

### ISSUE THREAD

**Issue by alittlealone** [HKUST-KnowComp/ASER#12]
Thank you for constructing such a great knowledge graph!
I install ASER successfully and can run the ASER extractor and a conceptualizer step-by-step. However, I met a problem while using client/server mode. When I type "aser-server" in the command line, it yield a ModuleNotFoundError:

Traceback (most recent call last):
  File "/u01/had/anaconda3/envs/pytorch/bin/aser-server", line 11, in <module>
    load_entry_point('aser==2.0.0', 'console_scripts', 'aser-server')()
  File "/u01/had/anaconda3/envs/pytorch/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/u01/had/anaconda3/envs/pytorch/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/u01/had/anaconda3/envs/pytorch/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/u01/had/anaconda3/envs/pytorch/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'aser'

Why it can't load aser module? Did I use it in the wrong way?

**Comment by seanliu96** [comment]
Hi, could you please try to `deactivate` and then `activate` your conda environment?

**Comment by alittlealone** [comment]
> Hi, could you please try to `deactivate` and then `activate` your conda environment?

Hi, I tried to deactivate and then activate my conda environment, the error is still here.
I also tried to use it without anaconda, but I still got the same error.
<img width="712" alt="Screen Shot 2021-05-09 at 8 07 59 PM" src="https://user-images.githubusercontent.com/8852062/117571854-e41ba500-b102-11eb-88a3-2f5b3c576c7e.png">

**Comment by seanliu96** [comment]
> > Hi, could you please try to `deactivate` and then `activate` your conda environment?
> 
> Hi, I tried to deactivate and then activate my conda environment, the error is still here.
> I also tried to use it without anaconda, but I still got the same error.
> <img alt="Screen Shot 2021-05-09 at 8 07 59 PM" width="712" src="https://user-images.githubusercontent.com/8852062/117571854-e41ba500-b102-11eb-88a3-2f5b3c576c7e.png">

Could you please try to uninstall "aser" and then install it again?

**Comment by alittlealone** [comment]
Uninstall and install again didn't solve the problem. I also tried on a different computer, and met the error again. This is so weird.

**Comment by seanliu96** [comment]
The bug is fixed by the recent commit (https://github.com/HKUST-KnowComp/ASER/commit/b00c6537d16db82acc59fa58dbad3d6c1e3a98bc).
