### ISSUE TITLE
An error when using ASER Pipeline Mode

### ISSUE THREAD

**Issue by pankaiqianghub** [HKUST-KnowComp/ASER#13]
thanks for providing such good code and it helps me a lot , but there is a small error when i using pipeline mode.
When using aser-pipe instruction, it comes out an error:
AttributeError: 'ASERPipe' object has no attribute 'parsed_readers'
I cannot figure it out and thank you a lot again.

**Comment by seanliu96** [comment]
Please use `python setup.py develop` temporarily. I will fix this bug later (due to the missing resource in site-packages).

**Comment by pankaiqianghub** [comment]
thanks a lot! I will try it again thanks.

**Comment by pankaiqianghub** [comment]
Hi, sorry for bothering you again, could you please tell me what is this code's output form. Is it a graph or text like what showed in get_started.ipynb like 

concepts:
[__PERSON__0 think,
 food toast,
 carbohydrate toast,
 item toast,
 starchy-food toast,
 product toast,

should I write another project to translate text to graph or there are some other types of output form and what is the final output? 
Thank you very very much!

**Comment by seanliu96** [comment]
Hi, if your problem has been solved, please close the issue to let others know. Thanks.

**Comment by seanliu96** [comment]
The returned results are the Eventuality and Relation objects. Please refer to the documentation to check the APIs.
