### ISSUE TITLE
A command failed

### ISSUE THREAD

**Issue by tkyk853isp** [HKUST-KnowComp/ASER#20]
I executed the following command.
```
aser-server -n_workers 1 -n_concurrent_back_socks 10 \
    -port 8000 -port_out 8001 \
    -corenlp_path "stanford-corenlp-3.9.2" -base_corenlp_port 9000 \
    -aser_kg_dir "core" -concept_kg_dir "concept" -probase_path "probase.txt"
```
Then I got the following log and it didn't go to the next step.
```
ASER Sink started
Connect to the ASER KG…
```
The directories "core" and "concept" respectively contain KG.db and concept.db from the data of ASER 2.0 in OneDrive ([link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/xliucr_connect_ust_hk/EnlOIunfqNRKsCQIBSXe9pQBL0KhLxTNMSNSJ3Mzt0bmhA?e=xm86PF)). There was no problem when I executed the command with KG.db and concept.db for the tutorial. Do you have any ideas of why it didn't go to the next step? 
I executed the command in a Docker container and the OS was Ubuntu 18.04 LTS. The computer I used has core i7 8C8T, 64GB RAM, and 1TB SSD.

**Comment by tkyk853isp** [comment]
I ran `java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000` and I got the following log.
```
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 8
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0.0.0.0:9000
```
Then I ran `aser-server -n_workers 1 -n_concurrent_back_socks 10 \ -port 8000 -port_out 8001 \ -corenlp_path "stanford-corenlp-3.9.2" -base_corenlp_port 9000 \ -aser_kg_dir "core" -concept_kg_dir "concept" -probase_path "probase.txt"`, but the result was the same.

**Comment by seanliu96** [comment]
It is just strange. We haven't faced this situation before. Could you please test the corenlp request via java or other programs? Because if you successfully create an extractor and send a request to the corenlp server, the corenlp will load some necessary packages and you can see the log.

**Comment by tkyk853isp** [comment]
When I pressed Ctrl+c while the log ```Connect to the ASER KG...``` is displayed, I got the following log.
```
  File "/usr/local/lib/python3.9/site-packages/zmq/decorators.py", line 76, in wrapper
Process ASERSink-1:
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/zmq/decorators.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/zmq/decorators.py", line 76, in wrapper
    return func(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/server/__init__.py", line 122, in _run
    self.aser_db = ASERDataBase(self.opt, db_addr_list, sink_receiver_addr)
  File "/usr/local/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/server/__init__.py", line 181, in __init__
    self.kg_conn = ASERKGConnection(db_path=os.path.join(opt.aser_kg_dir, "KG.db"), mode="cache")
  File "/usr/local/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/database/kg_connection.py", line 91, in __init__
    self.init()
  File "/usr/local/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/database/kg_connection.py", line 140, in init
    for e in self._conn.get_columns(self.eventuality_table_name, ["_id"]):
  File "/usr/local/lib/python3.9/site-packages/aser-2.0.0-py3.9.egg/aser/database/db_connection.py", line 225, in get_columns
    result = list(map(lambda x: OrderedDict(zip(columns, x)), self._conn.execute(select_table)))
sqlite3.OperationalError: database is locked
                                                                            
During handling of the above exception, another exception occurred:
...
```
I suspected that the cause of the error was mounting KG.db in the host machine to the Docker container in which I ran the commands, so I tried using a copy of mounted KG.db. Then it worked well. Thank you.

**Comment by seanliu96** [comment]
@tkyk853isp I never thought about the reason of the db file. Thanks so much for providing your solution and helping others.
