### ISSUE TITLE
AttributeError: 'list' object has no attribute 'skeleton_phrases'

### ISSUE THREAD

**Issue by JueXiuHuang** [HKUST-KnowComp/ASER#22]
Hi,
I tried to follow the example code to run ASER, and I got this error when I tried to conceptualize eventualities, how can I solve this problem?

thanks!

**Comment by JueXiuHuang** [comment]
I think I miss some details so I get this error, sorry for disturbing.

**Comment by seanliu96** [comment]
If you have any further questions, please feel free to ask!
