### ISSUE TITLE
Meaning of score

### ISSUE THREAD

**Issue by JueXiuHuang** [HKUST-KnowComp/ASER#26]
Hi,

In Step-by-step extraction tutorial, we can get a concept_instance_pairs object which contains list of concept, eventuality and their score.
What is the actual meaning of the score? Does it means that the probability of eventuality belongs to certain concept?
But tutorial page said that one eventuality can map into several concepts, so I think that the score might represent the weight that eventuality contains certain concept. But the sum of these weight doesn't equal to 1, or just because we didn't normalize the weight?
Which explanation is closer to the real one?

Thanks!!

**Comment by seanliu96** [comment]
Hi,

Thanks for your great question. The score computed at [concept.py#L165](https://github.com/HKUST-KnowComp/ASER/blob/master/aser/concept.py#L165). There are many ways to get the _score(instance, concept)_. The default is "likelihood", i.e., frequency(instance, concept) / frequency(instance).
More score functions can be found at [1].

[1] Z. Wang, H. Wang, J. Wen, Y. Xiao. An inference approach to basic level of categorization. In CIKM, 2015, pp. 653–662.
