### ISSUE TITLE
TypeError: first argument must be string or compiled pattern

### ISSUE THREAD

**Issue by JueXiuHuang** [HKUST-KnowComp/ASER#28]
Hi,
I tried to use ASER extractor to extract eventualities and concepts in novel chapter.
But when I pass the chapter text into extractor, it give above error message, how can I change the max length limit of extractor?

**Comment by seanliu96** [comment]
Add the max_char_length parameter in  https://github.com/HKUST-KnowComp/ASER/blob/master/aser/extract/utils.py#L93
(refer to [stanza](https://stanfordnlp.github.io/stanza/client_properties.html#corenlp-server-start-options-server))

**Comment by seanliu96** [comment]
But I still recommend you to mannually split one chapter into paragraphs due to the complexity.
