### ISSUE TITLE
Event in "concept.db"

### ISSUE THREAD

**Issue by wangbo9719** [HKUST-KnowComp/ASER#29]
I use the `KG = ASERKGConnection(concept_db_path, mode='memory')` to view the KG architecture. But the KG.eid is an empty set and I cannot get the exact information of an eid derived from rid.

Did I make some mistakes? How can I access the concept events contained in concept.db?

**Comment by wangbo9719** [comment]
By the way, the loading speed is too slow. It takes me 2.5h to load concept.db in memory mode. Is it normal?

**Comment by seanliu96** [comment]
For concept.db, please use aser.database.kg_connection.ASERConceptConnection.
For the loading, please keep in mind that there are more than 40GB concepts in disk, and your are suggested to have 300GB memory.

**Comment by wangbo9719** [comment]
Thanks for your quick reply.
