### ISSUE TITLE
Add gzip compression to downloadable files

### ISSUE THREAD

**Issue by LucaCappelletti94** [HKUST-KnowComp/ASER#31]
Hello, and thank you for making this resource.

I am downloading the KG files from [here](https://data.dgl.ai/dataset/ASER/README.txt).

I just wanted to point out that if the files were gzipped, they would likely weigh much less, making for shorter download times and, most notably for you guys, less space occupied on your server and fewer bandwidth costs to pay.

**Comment by seanliu96** [comment]
We have tried, but gzip and 7z cannot save too much space as the DB has already involved some technologies to help improve the space efficiency.

**Comment by LucaCappelletti94** [comment]
Oh ok! No problem then. I am almost done writing the small script to parse everything into a format that is compatible with what I'll be doing with it, is it okay if I upload the result on the web archive? That way it'll be a bit easier for me to download automatically on the different machines where I run stuff.

**Comment by seanliu96** [comment]
Sure, you can upload and share the processed data for nonprofit purposes.

**Comment by LucaCappelletti94** [comment]
Perfect, this is just for non-profit research so it should be quite ok. Thanks again!
