### ISSUE TITLE
ASER knowledge graph data base file is not accessible

### ISSUE THREAD

**Issue by AnilB87** [HKUST-KnowComp/ASER#5]
Executing the following line in ASER.ipynb gives an error:
kg_conn = KG_Connection(db_path=r'data/database/core/KG_v0.1.0.db', mode='cache')

sqlite3.OperationalError: unable to open database file

**Comment by AnilB87** [comment]
Found the data base file

**Comment by anerkami** [comment]
where can I find this database file?

**Comment by panda0881** [comment]
Hi,

You can check out our project page for download (
https://hkust-knowcomp.github.io/ASER/)

Best Regards,
Hongming

**Comment by anerkami** [comment]
ok, now I see it.
Thanks!

**Comment by anerkami** [comment]
yes, I see it now.
Thank you very much!
