### ISSUE TITLE
How can I get the db file "KG_v0.1.0.db" to access the data in the database?

### ISSUE THREAD

**Issue by snowcement** [HKUST-KnowComp/ASER#8]
Hi, thanks for your open-source code, and here is a question. When I call the API KG_Connection() in ASER.ipynb，
`kg_conn = KG_Connection(db_path=r'data/database/core/KG_v0.1.0.db', mode='cache')`

where can I find the file 'KG_v0.1.0.db'? There is no path of 'data/database/core/'. Thank you~

**Comment by panda0881** [comment]
You can try download it from the project page: https://hkust-knowcomp.github.io/ASER/
